on:
  push:
    branches:
      - "main"
    paths:
      - '.github/workflows/deployTest.yml'
jobs:
  infrastructure-provisioning:
    name: "provision infrastructure on Azure"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout action"
        uses: actions/checkout@v1
      # use credentials
      - name: "login to azure"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_LOGIN }}

      - name: "create resources"
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./ARM-Templates/container-webapp-template-test.json
