on:
  push:
    paths:
      - '.github/workflows/deployDev.yml'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      # use credentials
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_LOGIN }}
